# Namespace where the application will be deployed
namespace: "grafana"

alb:
  # Tags to associate with the Application Load Balancer
  tags: "Name=grafana-alb"

ingress:
  # Subnets for the ingress controller
  subnets: "subnet-12345678,subnet-23456789"
  # ACM certificate ARN for HTTPS
  certificateArn: "arn:aws:acm:us-west-2:123456789012:certificate/abcd1234-5678-90ab-cdef-1234567890ab"
  # Hostname for the ingress controller
  host: "grafana.example.com"
